### ISSUE TITLE
As a greenhouse owner I want to know light levels to notify when to close shutters

### ISSUE THREAD

**Issue by BruceMacD** [BruceMacD/GreenHouseMonitor#1]
Critical
Story points: 6 hours
Confidence: 7

Acceptance criteria:
- ID: AT 1.1
   Given: The user has set a range
   When: The light is returned far above the range
   Then: The app pushes a notification to alert the user the shutters need to be closed

**Comment by matt24smith** [comment]
added light level unit test code stub
