### ISSUE TITLE
As a greenhouse owner I want to know temperature for optimal growth

### ISSUE THREAD

**Issue by BruceMacD** [BruceMacD/GreenHouseMonitor#3]
Critical
Story points: 6 hours
Confidence: 7

Acceptance criteria:

Server:

- ID: AT 3.1
   Given: The app is connected to the Hexiwear
   When: The temperature is read by the Hexiwear
   Then: The temperature is received by the application
- ID: AT 3.2
   Given: The temperature is received by the application
   When: The temperature is read by the Hexiwear
   Then: The temperature is updated in the UI
- ID: AT 3.3
   Given: The temperature is received by the application
   When: The temperature is read by the Hexiwear
   Then: The temperature is within a realistic range

Client:

- ID: AT 3.4
  Given: The user receives data
  When: The user receives data
  Then: Check if data displayed

- ID: AT 3.5
  Given: The user receives data
  When: The user receives data
  Then: Check if data displayed is temperature

**Comment by matt24smith** [comment]
Added temperature unit test code stub
