### ISSUE TITLE
As a greenhouse owner I want to know when humidity is humidity is out of range

### ISSUE THREAD

**Issue by BruceMacD** [BruceMacD/GreenHouseMonitor#5]
Critical
Story points: 5 hours
Confidence: 6

Acceptance criteria:

Server:

- ID: AT 5.1
   Given: The humidity is received by the app
   When: The humidity is read
   Then: The value is checked to within the app's given range 
- ID: AT 5.2
   Given: The UI has an input for range
   When: The user sets the humidity range
   Then: The humidity returned is checked to be within this range

Client:

- ID: AT 5.3
  Given: The humidity data is received by the user
  When: The humidity data is read according to user specifications
  Then: The user gets a warning as to the current condition

**Comment by matt24smith** [comment]
added humidity level unit test code stub
